[2023-02-06 13:14:53 +0000] [92346] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/usr/local/bin/home/gunicorn.sock']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /usr/local/bin/home
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /usr/local/bin/home/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /usr/local/bin/home/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fbdd26cf250>
  on_reload: <function OnReload.on_reload at 0x7fbdd26cf370>
  when_ready: <function WhenReady.when_ready at 0x7fbdd26cf490>
  pre_fork: <function Prefork.pre_fork at 0x7fbdd26cf5b0>
  post_fork: <function Postfork.post_fork at 0x7fbdd26cf6d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fbdd26cf7f0>
  worker_int: <function WorkerInt.worker_int at 0x7fbdd26cf910>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fbdd26cfa30>
  pre_exec: <function PreExec.pre_exec at 0x7fbdd26cfb50>
  pre_request: <function PreRequest.pre_request at 0x7fbdd26cfc70>
  post_request: <function PostRequest.post_request at 0x7fbdd26cfd00>
  child_exit: <function ChildExit.child_exit at 0x7fbdd26cfe20>
  worker_exit: <function WorkerExit.worker_exit at 0x7fbdd26cff40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fbdd26e00d0>
  on_exit: <function OnExit.on_exit at 0x7fbdd26e01f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-06 13:14:53 +0000] [92346] [INFO] Starting gunicorn 20.1.0
[2023-02-06 13:14:53 +0000] [92346] [DEBUG] Arbiter booted
[2023-02-06 13:14:53 +0000] [92346] [INFO] Listening at: unix:/usr/local/bin/home/gunicorn.sock (92346)
[2023-02-06 13:14:53 +0000] [92346] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-06 13:14:53 +0000] [92347] [INFO] Booting worker with pid: 92347
[2023-02-06 13:14:53 +0000] [92348] [INFO] Booting worker with pid: 92348
[2023-02-06 13:14:53 +0000] [92346] [DEBUG] 2 workers
[2023-02-06 13:14:53 +0000] [92347] [INFO] Started server process [92347]
[2023-02-06 13:14:53 +0000] [92347] [INFO] Waiting for application startup.
[2023-02-06 13:14:53 +0000] [92347] [INFO] Application startup complete.
[2023-02-06 13:14:53 +0000] [92348] [INFO] Started server process [92348]
[2023-02-06 13:14:53 +0000] [92348] [INFO] Waiting for application startup.
[2023-02-06 13:14:53 +0000] [92348] [INFO] Application startup complete.
[2023-02-13 13:07:12 +0000] [92346] [INFO] Handling signal: term
[2023-02-13 13:07:12 +0000] [92347] [INFO] Shutting down
[2023-02-13 13:07:12 +0000] [92348] [INFO] Shutting down
[2023-02-13 13:07:12 +0000] [92347] [INFO] Waiting for application shutdown.
[2023-02-13 13:07:12 +0000] [92347] [INFO] Application shutdown complete.
[2023-02-13 13:07:12 +0000] [92347] [INFO] Finished server process [92347]
[2023-02-13 13:07:12 +0000] [92347] [INFO] Worker exiting (pid: 92347)
[2023-02-13 13:07:12 +0000] [92348] [INFO] Waiting for application shutdown.
[2023-02-13 13:07:12 +0000] [92348] [INFO] Application shutdown complete.
[2023-02-13 13:07:12 +0000] [92348] [INFO] Finished server process [92348]
[2023-02-13 13:07:12 +0000] [92348] [INFO] Worker exiting (pid: 92348)
[2023-02-13 13:07:13 +0000] [92346] [INFO] Shutting down: Master
[2023-02-13 13:07:15 +0000] [180680] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/usr/local/bin/home/gunicorn.sock']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /usr/local/bin/home
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /usr/local/bin/home/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /usr/local/bin/home/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f2bf00fb250>
  on_reload: <function OnReload.on_reload at 0x7f2bf00fb370>
  when_ready: <function WhenReady.when_ready at 0x7f2bf00fb490>
  pre_fork: <function Prefork.pre_fork at 0x7f2bf00fb5b0>
  post_fork: <function Postfork.post_fork at 0x7f2bf00fb6d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f2bf00fb7f0>
  worker_int: <function WorkerInt.worker_int at 0x7f2bf00fb910>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f2bf00fba30>
  pre_exec: <function PreExec.pre_exec at 0x7f2bf00fbb50>
  pre_request: <function PreRequest.pre_request at 0x7f2bf00fbc70>
  post_request: <function PostRequest.post_request at 0x7f2bf00fbd00>
  child_exit: <function ChildExit.child_exit at 0x7f2bf00fbe20>
  worker_exit: <function WorkerExit.worker_exit at 0x7f2bf00fbf40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f2bf01100d0>
  on_exit: <function OnExit.on_exit at 0x7f2bf01101f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-13 13:07:15 +0000] [180680] [INFO] Starting gunicorn 20.1.0
[2023-02-13 13:07:15 +0000] [180680] [DEBUG] Arbiter booted
[2023-02-13 13:07:15 +0000] [180680] [INFO] Listening at: unix:/usr/local/bin/home/gunicorn.sock (180680)
[2023-02-13 13:07:15 +0000] [180680] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-13 13:07:15 +0000] [180712] [INFO] Booting worker with pid: 180712
[2023-02-13 13:07:15 +0000] [180713] [INFO] Booting worker with pid: 180713
[2023-02-13 13:07:15 +0000] [180680] [DEBUG] 2 workers
[2023-02-13 13:07:16 +0000] [180712] [INFO] Started server process [180712]
[2023-02-13 13:07:16 +0000] [180712] [INFO] Waiting for application startup.
[2023-02-13 13:07:16 +0000] [180712] [INFO] Application startup complete.
[2023-02-13 13:07:16 +0000] [180713] [INFO] Started server process [180713]
[2023-02-13 13:07:16 +0000] [180713] [INFO] Waiting for application startup.
[2023-02-13 13:07:16 +0000] [180713] [INFO] Application startup complete.
[2023-02-13 14:09:52 +0000] [180680] [INFO] Handling signal: term
[2023-02-13 14:09:52 +0000] [180713] [INFO] Shutting down
[2023-02-13 14:09:52 +0000] [180712] [INFO] Shutting down
[2023-02-13 14:09:52 +0000] [180713] [INFO] Waiting for application shutdown.
[2023-02-13 14:09:52 +0000] [180713] [INFO] Application shutdown complete.
[2023-02-13 14:09:52 +0000] [180713] [INFO] Finished server process [180713]
[2023-02-13 14:09:52 +0000] [180712] [INFO] Waiting for application shutdown.
[2023-02-13 14:09:52 +0000] [180712] [INFO] Application shutdown complete.
[2023-02-13 14:09:52 +0000] [180712] [INFO] Finished server process [180712]
[2023-02-13 14:09:52 +0000] [180712] [INFO] Worker exiting (pid: 180712)
[2023-02-13 14:09:52 +0000] [180713] [INFO] Worker exiting (pid: 180713)
[2023-02-13 14:09:53 +0000] [180680] [INFO] Shutting down: Master
[2023-02-13 14:10:06 +0000] [181977] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/usr/local/bin/home/gunicorn.sock']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /usr/local/bin/home
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /usr/local/bin/home/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /usr/local/bin/home/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fe72683b250>
  on_reload: <function OnReload.on_reload at 0x7fe72683b370>
  when_ready: <function WhenReady.when_ready at 0x7fe72683b490>
  pre_fork: <function Prefork.pre_fork at 0x7fe72683b5b0>
  post_fork: <function Postfork.post_fork at 0x7fe72683b6d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fe72683b7f0>
  worker_int: <function WorkerInt.worker_int at 0x7fe72683b910>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fe72683ba30>
  pre_exec: <function PreExec.pre_exec at 0x7fe72683bb50>
  pre_request: <function PreRequest.pre_request at 0x7fe72683bc70>
  post_request: <function PostRequest.post_request at 0x7fe72683bd00>
  child_exit: <function ChildExit.child_exit at 0x7fe72683be20>
  worker_exit: <function WorkerExit.worker_exit at 0x7fe72683bf40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fe7268500d0>
  on_exit: <function OnExit.on_exit at 0x7fe7268501f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-13 14:10:06 +0000] [181977] [INFO] Starting gunicorn 20.1.0
[2023-02-13 14:10:06 +0000] [181977] [DEBUG] Arbiter booted
[2023-02-13 14:10:06 +0000] [181977] [INFO] Listening at: unix:/usr/local/bin/home/gunicorn.sock (181977)
[2023-02-13 14:10:06 +0000] [181977] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-13 14:10:06 +0000] [181978] [INFO] Booting worker with pid: 181978
[2023-02-13 14:10:06 +0000] [181979] [INFO] Booting worker with pid: 181979
[2023-02-13 14:10:06 +0000] [181977] [DEBUG] 2 workers
[2023-02-13 14:10:08 +0000] [181978] [INFO] Started server process [181978]
[2023-02-13 14:10:08 +0000] [181978] [INFO] Waiting for application startup.
[2023-02-13 14:10:08 +0000] [181978] [INFO] Application startup complete.
[2023-02-13 14:10:08 +0000] [181979] [INFO] Started server process [181979]
[2023-02-13 14:10:08 +0000] [181979] [INFO] Waiting for application startup.
[2023-02-13 14:10:08 +0000] [181979] [INFO] Application startup complete.
[2023-02-13 14:24:22 +0000] [181977] [INFO] Handling signal: term
[2023-02-13 14:24:22 +0000] [181979] [INFO] Shutting down
[2023-02-13 14:24:22 +0000] [181978] [INFO] Shutting down
[2023-02-13 14:24:22 +0000] [181979] [INFO] Waiting for application shutdown.
[2023-02-13 14:24:22 +0000] [181979] [INFO] Application shutdown complete.
[2023-02-13 14:24:22 +0000] [181979] [INFO] Finished server process [181979]
[2023-02-13 14:24:22 +0000] [181979] [INFO] Worker exiting (pid: 181979)
[2023-02-13 14:24:22 +0000] [181978] [INFO] Waiting for application shutdown.
[2023-02-13 14:24:22 +0000] [181978] [INFO] Application shutdown complete.
[2023-02-13 14:24:22 +0000] [181978] [INFO] Finished server process [181978]
[2023-02-13 14:24:22 +0000] [181978] [INFO] Worker exiting (pid: 181978)
[2023-02-13 14:24:23 +0000] [181977] [INFO] Shutting down: Master
[2023-02-13 14:24:24 +0000] [182157] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/usr/local/bin/home/gunicorn.sock']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /usr/local/bin/home
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /usr/local/bin/home/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /usr/local/bin/home/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f947d607250>
  on_reload: <function OnReload.on_reload at 0x7f947d607370>
  when_ready: <function WhenReady.when_ready at 0x7f947d607490>
  pre_fork: <function Prefork.pre_fork at 0x7f947d6075b0>
  post_fork: <function Postfork.post_fork at 0x7f947d6076d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f947d6077f0>
  worker_int: <function WorkerInt.worker_int at 0x7f947d607910>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f947d607a30>
  pre_exec: <function PreExec.pre_exec at 0x7f947d607b50>
  pre_request: <function PreRequest.pre_request at 0x7f947d607c70>
  post_request: <function PostRequest.post_request at 0x7f947d607d00>
  child_exit: <function ChildExit.child_exit at 0x7f947d607e20>
  worker_exit: <function WorkerExit.worker_exit at 0x7f947d607f40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f947d61c0d0>
  on_exit: <function OnExit.on_exit at 0x7f947d61c1f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-13 14:24:24 +0000] [182157] [INFO] Starting gunicorn 20.1.0
[2023-02-13 14:24:24 +0000] [182157] [DEBUG] Arbiter booted
[2023-02-13 14:24:24 +0000] [182157] [INFO] Listening at: unix:/usr/local/bin/home/gunicorn.sock (182157)
[2023-02-13 14:24:24 +0000] [182157] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-13 14:24:24 +0000] [182160] [INFO] Booting worker with pid: 182160
[2023-02-13 14:24:24 +0000] [182161] [INFO] Booting worker with pid: 182161
[2023-02-13 14:24:24 +0000] [182157] [DEBUG] 2 workers
[2023-02-13 14:24:26 +0000] [182160] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/bin/home/app.py", line 8, in <module>
    from transformers import pipeline
ModuleNotFoundError: No module named 'transformers'
[2023-02-13 14:24:26 +0000] [182160] [INFO] Worker exiting (pid: 182160)
[2023-02-13 14:24:26 +0000] [182161] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/bin/home/app.py", line 8, in <module>
    from transformers import pipeline
ModuleNotFoundError: No module named 'transformers'
[2023-02-13 14:24:26 +0000] [182161] [INFO] Worker exiting (pid: 182161)
[2023-02-13 14:24:48 +0000] [182175] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/usr/local/bin/home/gunicorn.sock']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /usr/local/bin/home
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /usr/local/bin/home/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /usr/local/bin/home/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f9980173250>
  on_reload: <function OnReload.on_reload at 0x7f9980173370>
  when_ready: <function WhenReady.when_ready at 0x7f9980173490>
  pre_fork: <function Prefork.pre_fork at 0x7f99801735b0>
  post_fork: <function Postfork.post_fork at 0x7f99801736d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f99801737f0>
  worker_int: <function WorkerInt.worker_int at 0x7f9980173910>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f9980173a30>
  pre_exec: <function PreExec.pre_exec at 0x7f9980173b50>
  pre_request: <function PreRequest.pre_request at 0x7f9980173c70>
  post_request: <function PostRequest.post_request at 0x7f9980173d00>
  child_exit: <function ChildExit.child_exit at 0x7f9980173e20>
  worker_exit: <function WorkerExit.worker_exit at 0x7f9980173f40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f99801880d0>
  on_exit: <function OnExit.on_exit at 0x7f99801881f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-13 14:24:48 +0000] [182175] [INFO] Starting gunicorn 20.1.0
[2023-02-13 14:24:48 +0000] [182175] [DEBUG] Arbiter booted
[2023-02-13 14:24:48 +0000] [182175] [INFO] Listening at: unix:/usr/local/bin/home/gunicorn.sock (182175)
[2023-02-13 14:24:48 +0000] [182175] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-13 14:24:48 +0000] [182176] [INFO] Booting worker with pid: 182176
[2023-02-13 14:24:48 +0000] [182175] [DEBUG] 2 workers
[2023-02-13 14:24:48 +0000] [182177] [INFO] Booting worker with pid: 182177
[2023-02-13 14:24:50 +0000] [182176] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/bin/home/app.py", line 8, in <module>
    from transformers import pipeline
ModuleNotFoundError: No module named 'transformers'
[2023-02-13 14:24:50 +0000] [182176] [INFO] Worker exiting (pid: 182176)
[2023-02-13 14:24:50 +0000] [182177] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/dist-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/bin/home/app.py", line 8, in <module>
    from transformers import pipeline
ModuleNotFoundError: No module named 'transformers'
[2023-02-13 14:24:50 +0000] [182177] [INFO] Worker exiting (pid: 182177)
[2023-02-13 14:24:51 +0000] [182175] [WARNING] Worker with pid 182177 was terminated due to signal 15
[2023-02-13 14:24:51 +0000] [182175] [INFO] Shutting down: Master
[2023-02-13 14:24:51 +0000] [182175] [INFO] Reason: Worker failed to boot.
[2023-02-13 14:34:08 +0000] [182374] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/usr/local/bin/home/gunicorn.sock']
  backlog: 2048
  workers: 2
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /usr/local/bin/home
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 0
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /usr/local/bin/home/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /usr/local/bin/home/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7ff94303f250>
  on_reload: <function OnReload.on_reload at 0x7ff94303f370>
  when_ready: <function WhenReady.when_ready at 0x7ff94303f490>
  pre_fork: <function Prefork.pre_fork at 0x7ff94303f5b0>
  post_fork: <function Postfork.post_fork at 0x7ff94303f6d0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7ff94303f7f0>
  worker_int: <function WorkerInt.worker_int at 0x7ff94303f910>
  worker_abort: <function WorkerAbort.worker_abort at 0x7ff94303fa30>
  pre_exec: <function PreExec.pre_exec at 0x7ff94303fb50>
  pre_request: <function PreRequest.pre_request at 0x7ff94303fc70>
  post_request: <function PostRequest.post_request at 0x7ff94303fd00>
  child_exit: <function ChildExit.child_exit at 0x7ff94303fe20>
  worker_exit: <function WorkerExit.worker_exit at 0x7ff94303ff40>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7ff9430540d0>
  on_exit: <function OnExit.on_exit at 0x7ff9430541f0>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2023-02-13 14:34:08 +0000] [182374] [INFO] Starting gunicorn 20.1.0
[2023-02-13 14:34:08 +0000] [182374] [DEBUG] Arbiter booted
[2023-02-13 14:34:08 +0000] [182374] [INFO] Listening at: unix:/usr/local/bin/home/gunicorn.sock (182374)
[2023-02-13 14:34:08 +0000] [182374] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-02-13 14:34:08 +0000] [182375] [INFO] Booting worker with pid: 182375
[2023-02-13 14:34:08 +0000] [182376] [INFO] Booting worker with pid: 182376
[2023-02-13 14:34:08 +0000] [182374] [DEBUG] 2 workers
[2023-02-13 14:34:10 +0000] [182375] [INFO] Started server process [182375]
[2023-02-13 14:34:10 +0000] [182376] [INFO] Started server process [182376]
[2023-02-13 14:34:10 +0000] [182376] [INFO] Waiting for application startup.
[2023-02-13 14:34:10 +0000] [182376] [INFO] Application startup complete.
[2023-02-13 14:34:10 +0000] [182375] [INFO] Waiting for application startup.
[2023-02-13 14:34:10 +0000] [182375] [INFO] Application startup complete.
[2023-02-13 15:53:45 +0000] [182376] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/bin/home/app.py", line 44, in hello_name
    return {'message': f'Welcome to GeeksforGeeks!, {nam}'}
NameError: name 'nam' is not defined
